#!/usr/bin/env python
import argparse
from scapy.all import IP,ICMP,send

CHUNKSIZE = 56

def main(destination, infile, no_chunk):
    data = infile.read()
    ip = IP(dst=destination)
    chunks = []
    if no_chunk:
        chunks.append(data)
    else:
        chunks = [data[index:index+CHUNKSIZE] \
                  for index in range(0, len(data), CHUNKSIZE)]
    for chunk in chunks:
        pass
        # Build packets and send in sequence

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data as an icmp payload')
    parser.add_argument('--nochunk', '-n', action='store_true',
                        help='don\'t break data into 56 byte chunks')
    parser.add_argument('destination', type=str)
    parser.add_argument('file', type=argparse.FileType('rb'))
    args = parser.parse_args()
    main(args.destination, args.file, args.nochunk)
